### ISSUE TITLE
Implement Land/Sea filtering with the new dataset that covers the whole Bali.  Moving this to as a new issue

### ISSUE THREAD

**Issue by REDummy** [ngelana/capstone-ngelana#10]
Implement Land/Sea filtering with the new dataset that covers the whole Bali.  Moving this to as a new issue

_Originally posted by @REDummy in https://github.com/ngelana/capstone-ngelana/issues/1#issuecomment-2148064921_

**Comment by anggerbudi** [comment]
Can't be more accurate since GSI program shape is like that
