### ISSUE TITLE
ML - Rework Coordinate Mapping

### ISSUE THREAD

**Issue by REDummy** [ngelana/capstone-ngelana#16]
Due to a few locations with not much establishment, we are burning a lot of API calls. Need to partition the mapping to segments or parts, focusing on the more populated/ city area.

**Comment by anggerbudi** [comment]
Already optimized in latest commit. Reduce points count from 6.4K to 4.7K

Still can't remove point in Banyuwangi section

**Comment by anggerbudi** [comment]
Closing issue due to the points in Banyuwangi is unrelated problem
